#**********************************************************************  
#	*주의 사항
#		현재 스크립트 파일은 파일명만 출력되어 있습니다.
#		따라서, 저장된 추출 결과 파일의 경로를 'read.table' 또는 'read.fwf'에 추가하여야 합니다.
#	예) 다운로드 받은 폴더명 : C:\Download
#	  ※ 파일 경로 추가 : "[다운로드 받은 폴더명]\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt"
# 		read.table("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#		또는
#		read.fwf("C:\Download\기업활동조사_기업활동조사(제공)_2019_20191201_92007.txt", ~~~
#
#		R 스크립트는 R 에서 파일 경로만 수정하시면 바로 실행(Ctrl+Alt+R)가능하며,
#		데이터셋 생성 후에 R 의 여러 가지 분석 기능을 사용할 수 있습니다.
#
#**********************************************************************

install.packages("dplyr")
library(dplyr)

mdis <- read.table("인구주택총조사_1%_인구사항(제공)_2015_20200229_87613.csv", header=FALSE, sep=",", colClasses = c("character"
, "character", "character", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "numeric"
, "numeric", "numeric", "numeric", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character", "character"
, "character", "character", "character", "character", "character", "character", "character", "character", "character", "numeric"), skip=1, na.string=c("*","**","***","****","*****","******","*******","********","*********","**********","."))

        mdis$V3<- recode_factor(mdis$V3, '1'="남자")
        mdis$V3<- recode_factor(mdis$V3, '2'="여자")
        mdis$V5<- recode_factor(mdis$V5, '01'="가구주(본인)")
        mdis$V5<- recode_factor(mdis$V5, '02'="배우자")
        mdis$V5<- recode_factor(mdis$V5, '03'="자녀")
        mdis$V5<- recode_factor(mdis$V5, '04'="자녀의 배우자")
        mdis$V5<- recode_factor(mdis$V5, '05'="가구주의 부모")
        mdis$V5<- recode_factor(mdis$V5, '06'="배우자의 부모")
        mdis$V5<- recode_factor(mdis$V5, '07'="친손자, 친손녀 및 그 배우자")
        mdis$V5<- recode_factor(mdis$V5, '08'="외손자, 외손녀 및 그 배우자")
        mdis$V5<- recode_factor(mdis$V5, '09'="증손자, 증손녀 및 그 배우자")
        mdis$V5<- recode_factor(mdis$V5, '10'="조부모")
        mdis$V5<- recode_factor(mdis$V5, '11'="형제자매 및 그 배우자")
        mdis$V5<- recode_factor(mdis$V5, '12'="형제자매의 자녀 및 그 배우자")
        mdis$V5<- recode_factor(mdis$V5, '13'="부모의 형제자매 및 그 배우자")
        mdis$V5<- recode_factor(mdis$V5, '14'="기타 친척, 인척")
        mdis$V5<- recode_factor(mdis$V5, '15'="그 외에 같이 사는 사람")
        mdis$V6<- recode_factor(mdis$V6, '1'="대한민국")
        mdis$V6<- recode_factor(mdis$V6, '2'="외국")
        mdis$V7<- recode_factor(mdis$V7, '1'="대한민국")
        mdis$V7<- recode_factor(mdis$V7, '2'="외국")
        mdis$V8<- recode_factor(mdis$V8, '1'="있음")
        mdis$V8<- recode_factor(mdis$V8, '2'="없음")
        mdis$V9<- recode_factor(mdis$V9, '1'="안 받았음(미취학 포함)")
        mdis$V9<- recode_factor(mdis$V9, '2'="초등학교")
        mdis$V9<- recode_factor(mdis$V9, '3'="중학교")
        mdis$V9<- recode_factor(mdis$V9, '4'="고등학교")
        mdis$V9<- recode_factor(mdis$V9, '5'="대학(4년제 미만)")
        mdis$V9<- recode_factor(mdis$V9, '6'="대학교(4년제 이상)")
        mdis$V9<- recode_factor(mdis$V9, '7'="대학원 석사 과정")
        mdis$V9<- recode_factor(mdis$V9, '8'="대학원 박사 과정")
        mdis$V10<- recode_factor(mdis$V10, '1'="졸업")
        mdis$V10<- recode_factor(mdis$V10, '2'="재학")
        mdis$V10<- recode_factor(mdis$V10, '3'="수료")
        mdis$V10<- recode_factor(mdis$V10, '4'="휴학")
        mdis$V10<- recode_factor(mdis$V10, '5'="중퇴")
        mdis$V11<- recode_factor(mdis$V11, '1'="현재 살고 있는 집")
        mdis$V11<- recode_factor(mdis$V11, '2'="같은 시,군,구 내 다른 집")
        mdis$V11<- recode_factor(mdis$V11, '3'="다른 시,군,구")
        mdis$V11<- recode_factor(mdis$V11, '4'="북한 또는 외국")
        mdis$V12<- recode_factor(mdis$V12, '1'="태어나지 않았음")
        mdis$V12<- recode_factor(mdis$V12, '2'="현재 살고 있는 집")
        mdis$V12<- recode_factor(mdis$V12, '3'="같은 시,군,구내 다른 집")
        mdis$V12<- recode_factor(mdis$V12, '4'="다른 시,군,구")
        mdis$V12<- recode_factor(mdis$V12, '5'="북한 또는 외국")
        mdis$V13<- recode_factor(mdis$V13, '1'="태어나지 않았음")
        mdis$V13<- recode_factor(mdis$V13, '2'="현재 살고 있는 집")
        mdis$V13<- recode_factor(mdis$V13, '3'="같은 시,군,구내 다른 집")
        mdis$V13<- recode_factor(mdis$V13, '4'="다른 시,군,구")
        mdis$V13<- recode_factor(mdis$V13, '5'="북한 또는 외국")
        mdis$V39<- recode_factor(mdis$V39, '1'="통근함")
        mdis$V39<- recode_factor(mdis$V39, '2'="통학함")
        mdis$V39<- recode_factor(mdis$V39, '3'="안함")
        mdis$V40<- recode_factor(mdis$V40, '1'="현재 살고 있는 읍,면,동")
        mdis$V40<- recode_factor(mdis$V40, '2'="다른 읍,면,동")
        mdis$V53<- recode_factor(mdis$V53, '1'="주로 일하였음")
        mdis$V53<- recode_factor(mdis$V53, '2'="가사, 학업(학교, 학원) 등 다른 활동을 하면서 틈틈이 일하였음")
        mdis$V53<- recode_factor(mdis$V53, '3'="일자리를 갖고 있으나, 휴가 등으로 잠시 쉬고 있음")
        mdis$V53<- recode_factor(mdis$V53, '4'="일하지 않았음")
        mdis$V54<- recode_factor(mdis$V54, '1'="임금근로자")
        mdis$V54<- recode_factor(mdis$V54, '2'="고용원이 없는 자영업자")
        mdis$V54<- recode_factor(mdis$V54, '3'="고용원이 있는 자영업자")
        mdis$V54<- recode_factor(mdis$V54, '4'="무급 가족 종사자")
        mdis$V55<- recode_factor(mdis$V55, 'A'="농업, 임업 및 어업")
        mdis$V55<- recode_factor(mdis$V55, 'B'="광업")
        mdis$V55<- recode_factor(mdis$V55, 'C'="제조업")
        mdis$V55<- recode_factor(mdis$V55, 'D'="전기,가스,증기 및 수도사업")
        mdis$V55<- recode_factor(mdis$V55, 'E'="하수 폐기물처리, 원료재생 및 환경복원업")
        mdis$V55<- recode_factor(mdis$V55, 'F'="건설업")
        mdis$V55<- recode_factor(mdis$V55, 'G'="도매 및 소매업")
        mdis$V55<- recode_factor(mdis$V55, 'H'="운수업")
        mdis$V55<- recode_factor(mdis$V55, 'I'="숙박 및 음식점업")
        mdis$V55<- recode_factor(mdis$V55, 'J'="출판, 영상 방송통신 및 정보서비스업")
        mdis$V55<- recode_factor(mdis$V55, 'K'="금융 및 보험업")
        mdis$V55<- recode_factor(mdis$V55, 'L'="부동산업 및 임대업")
        mdis$V55<- recode_factor(mdis$V55, 'M'="전문,과학 및 기술서비스업")
        mdis$V55<- recode_factor(mdis$V55, 'N'="사업시설관리 및 사업지원서비스업")
        mdis$V55<- recode_factor(mdis$V55, 'O'="공공행정, 국방 및 사회보장행정")
        mdis$V55<- recode_factor(mdis$V55, 'P'="교육서비스업")
        mdis$V55<- recode_factor(mdis$V55, 'Q'="보건업 및 사회복지서비스업")
        mdis$V55<- recode_factor(mdis$V55, 'R'="예술, 스포츠 및 여가 관련 서비스업")
        mdis$V55<- recode_factor(mdis$V55, 'S'="협회 및 단체, 수리 및 기타 개인서비스업")
        mdis$V55<- recode_factor(mdis$V55, 'T'="가구 내 고용활동 및 달리 분류되지 않은 자가생산활동")
        mdis$V55<- recode_factor(mdis$V55, 'U'="국제 및 외국기관")
        mdis$V56<- recode_factor(mdis$V56, '1'="관리자")
        mdis$V56<- recode_factor(mdis$V56, '2'="전문가 및 관련 종사자")
        mdis$V56<- recode_factor(mdis$V56, '3'="사무 종사자")
        mdis$V56<- recode_factor(mdis$V56, '4'="서비스 종사자")
        mdis$V56<- recode_factor(mdis$V56, '5'="판매 종사자")
        mdis$V56<- recode_factor(mdis$V56, '6'="농림어업 숙련 종사자")
        mdis$V56<- recode_factor(mdis$V56, '7'="기능원 및 관련 기능 종사자")
        mdis$V56<- recode_factor(mdis$V56, '8'="장치기계 조작 및 조립 종사자")
        mdis$V56<- recode_factor(mdis$V56, '9'="단순노무 종사자")
        mdis$V56<- recode_factor(mdis$V56, 'A'="기타")
        mdis$V57<- recode_factor(mdis$V57, '1'="6개월 미만")
        mdis$V57<- recode_factor(mdis$V57, '2'="6개월~12개월 미만")
        mdis$V57<- recode_factor(mdis$V57, '3'="1년~3년 미만")
        mdis$V57<- recode_factor(mdis$V57, '4'="3년~5년 미만")
        mdis$V57<- recode_factor(mdis$V57, '5'="5년~10년 미만")
        mdis$V57<- recode_factor(mdis$V57, '6'="10년~15년 미만")
        mdis$V57<- recode_factor(mdis$V57, '7'="15년~20년 미만")
        mdis$V57<- recode_factor(mdis$V57, '8'="20년 이상")
        mdis$V58<- recode_factor(mdis$V58, '1'="사업장(건물 및 땅)")
        mdis$V58<- recode_factor(mdis$V58, '2'="자기 집")
        mdis$V58<- recode_factor(mdis$V58, '3'="남의 집")
        mdis$V58<- recode_factor(mdis$V58, '4'="거리")
        mdis$V58<- recode_factor(mdis$V58, '5'="야외 작업 현장")
        mdis$V58<- recode_factor(mdis$V58, '6'="운송 수단")
        mdis$V58<- recode_factor(mdis$V58, '7'="기타")
        mdis$V59<- recode_factor(mdis$V59, '1'="미혼")
        mdis$V59<- recode_factor(mdis$V59, '2'="배우자 있음")
        mdis$V59<- recode_factor(mdis$V59, '3'="사별")
        mdis$V59<- recode_factor(mdis$V59, '4'="이혼")
        mdis$V60<- recode_factor(mdis$V60, '1'="15세미만")
        mdis$V60<- recode_factor(mdis$V60, '2'="15-19세")
        mdis$V60<- recode_factor(mdis$V60, '3'="20-24세")
        mdis$V60<- recode_factor(mdis$V60, '4'="25-29세")
        mdis$V60<- recode_factor(mdis$V60, '5'="30-34세")
        mdis$V60<- recode_factor(mdis$V60, '6'="35-39세")
        mdis$V60<- recode_factor(mdis$V60, '7'="40세이상")
        mdis$V65<- recode_factor(mdis$V65, '1'="있음")
        mdis$V65<- recode_factor(mdis$V65, '2'="없음")
        mdis$V66<- recode_factor(mdis$V66, '1'="1명")
        mdis$V66<- recode_factor(mdis$V66, '2'="2명")
        mdis$V66<- recode_factor(mdis$V66, '3'="3명")
        mdis$V66<- recode_factor(mdis$V66, '4'="4명 이상")
        mdis$V67<- recode_factor(mdis$V67, '1'="있음")
        mdis$V67<- recode_factor(mdis$V67, '2'="없음")
        mdis$V68<- recode_factor(mdis$V68, '1'="있음")
        mdis$V68<- recode_factor(mdis$V68, '2'="없음")

colnames(mdis) = c("가구일련번호"
, "가구원번호", "성별", "만나이", "가구주와의 관계", "출생시국적(대한민국여부)", "현재국적(대한민국여부)", "종교유무", "교육정도(학력)", "교육정도(상태)", "출생지", "1년 전 거주지", "5년 전 거주지", "아동보육-부모", "아동보육-조부모(친가,외가)", "아동보육-기타 가족 또는 친인척", "아동보육-가사도우미, 이웃사람", "아동보육-유치원", "아동보육-어린이집, 놀이방", "아동보육-기타 보육시설", "아동보육-방과 후 학교"
, "아동보육-학원(예체능 포함)", "아동보육-혼자 또는 아동끼리 지냄", "아동보육-기타", "활동제약-시각장애", "활동제약-청각장애", "활동제약-언어장애", "활동제약-치매", "활동제약-뇌졸증(중풍)", "활동제약-걷기, 계단오르기, 들고 운반하기 등에 어려움이 있는 육체적 제약", "활동제약-지적, 자폐성 장애", "활동제약-정신적 질환 등 정신적 제약", "활동제약-제약없음", "일상생활 및 사회활동제약-배우기, 기억하기, 집중하기", "일상생활 및 사회활동제약-옷입기, 목욕하기, 밥먹기, 집안돌아다니기", "일상생활 및 사회활동제약-장보기, 병원가기, 집밖돌아다니기", "일상생활 및 사회활동제약-(16세이상)취업활동", "일상생활 및 사회활동제약-제약없음", "통근통학여부", "통근통학장소", "이용교통수단-걸어서"
, "이용교통수단-승용차, 소형승합차", "이용교통수단-시내, 좌석, 마을버스", "이용교통수단-통근, 통학버스", "이용교통수단-고속, 시외버스", "이용교통수단-전철, 지하철", "이용교통수단-기차", "이용교통수단-택시", "이용교통수단-자전거", "이용교통수단-기타", "통근통학소요시간(시간)", "통근통학소요시간(분)", "경제활동상태", "종사상지위", "산업대분류", "직업대분류", "현직업근무연수", "근로장소", "혼인상태", "초혼연령", "남아출산수"
, "여아출산수", "남아사망수", "여아사망수", "추가계획자녀여부", "추가계획자녀수", "결혼 전 취업여부", "경력단절여부", "사회활동-사회분야단체", "사회활동-경제분야단체", "사회활동-문화분야단체", "사회활동-정치분야단체", "사회활동-종교분야단체", "사회활동-지역단체", "사회활동-친목단체", "사회활동-교육단체", "사회활동-기타", "사회활동-없음", "고령자 생활비 원천-본인, 배우자의 일, 직업", "고령자 생활비 원천-예금, 적금", "고령자 생활비 원천-공적연금"
, "고령자 생활비 원천-개인연금", "고령자 생활비 원천-부동산", "고령자 생활비 원천-주식, 펀드, 채권 등", "고령자 생활비 원천-함께 사는 자녀", "고령자 생활비 원천-따로 사는 자녀", "고령자 생활비 원천-친척, 인척", "고령자 생활비 원천-국가 및 지방자치단체의 보조", "고령자 생활비 원천-이웃, 종교단체, 사회단체의 보조", "고령자 생활비 원천-기타", "인구가중치")

